matrix:
  include:
    - language: node_js

      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      
      cache:
        directories:
          - ./node_modules  

        script:
          - bash ./travis/test_node.sh
